spring:
  application:
    name: small-banking
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update